version: '3.8'

services:
  # # API Server

  # clearml-apiserver:
  #   extends:
  #     file: /opt/clearml/docker-compose.yml
  #     service: apiserver

  # # Web Server
  # clearml-webserver:
  #   extends:
  #     file: /opt/clearml/docker-compose.yml
  #     service: webserver

  # # File Server
  # clearml-fileserver:
  #   extends:
  #     file: /opt/clearml/docker-compose.yml
  #     service: fileserver


  app:
    build: /Users/sreeharshnamani/Downloads/Assignments_NYU/ai_rag/app  # Make sure to have a Dockerfile in the 'app' directory for configuring your Python environment
    container_name: app
    ports:
      - "8000:8000"  # Expose your application port
    volumes:
      - /Users/sreeharshnamani/Downloads/Assignments_NYU/ai_rag/app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - HUGGINGFACE_HUB_API_TOKEN=<your_huggingface_token>  # Replace or set via an env variable for security
    depends_on:
      - mongodb
      - qdrant
      # - clearml-apiserver

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=#rag_project  # Change this for security

  qdrant:
    image: qdrant/qdrant:v1.4.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage


volumes:
  mongodb_data:
  qdrant_data:
  clearml_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge